name: CI

on:
  push:
    branches: [add-github-actions]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: echo $SERVICE_ACCOUNT_JSON > serviceAccount.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      - run: npm i yarn
      - run: ./node_modules/.bin/yarn firestore:copy data/database/speakers.json speakers

          
